name: CoverIQ AutoTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-maintenance:
    runs-on: ubuntu-latest
    env:
      REPO_URL: ${{ secrets.REPO_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |

          pip install -r requirements.txt
      - name: Run test impact analyzer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          REPO=${REPO_URL:-https://github.com/tensorflow/gan.git}
          echo "Using repo: $REPO"
          python RegressionTest/main.py $REPO
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-maintenance-report
          path: RegressionTest/report.md